 version: '3.8'
 
 services:
   xconfui:
     build:
       context: ./xconfui
       dockerfile: Dockerfile
     ports:
       - "9393:9393"
     container_name: xconfui
     restart: always
 
   xconfwebconfig:
     build:
       context: ./xconfwebconfig
       dockerfile: Dockerfile
     ports:
       - "9001:9001"
     container_name: xconfwebconfig
     restart: always
 
   xconfadmin:
     build:
       context: ./xconfadmin
       dockerfile: Dockerfile
     ports:
       - "9000:9000"
     container_name: xconfadmin
     restart: always
 
